### PR TITLE
Dynamically determine controller API location in client-side Javascript

### LINKED ISSUE #225: Have dashboard determine API location dynamically
As per a report on the CARTA users slack login fails when a custom API address is specified in the CARTA configuration.  This is due to the client-side controller Javascript using a hardcoded API location rather than one specified in the config file.

### PR DESCRIPTION
**Pull request by daikema**
This fixes #225 by having the dashboard javascript dynamically load the CARTA config location which is then used to determine the location of the CARTA API for making requests.

### CODE REVIEW

File: public/dashboard.js [hunk 1]
```diff
@@ -21,6 +20,24 @@ let tokenExpiryTime = -1;
 let serverRunning = false;
 let notyf;
 
+let apiBase;
+getApiBase = async () => {
+    console.log("Called getApiBase")
```
Comment (veggiesaurus) [inline public/dashboard.js]: if we need this for debugging make it `console.debug`, but perhaps it's not needed?

**Review by veggiesaurus — CHANGES_REQUESTED** [review]

**Comment by daikema** [comment]
Trimmed the console log statement.  Going to use a separate PR to handle broader changes that might be needed when working with a reverse proxy.
